title: Yulian Hartadi
description: AI Automation Specialist UMKM Food & Beverage
theme: minima

url: "https://yulianhartadi71.github.io"
baseurl: ""

author: Yulian Hartadi
lang: id

permalink: /:categories/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
